### ISSUE TITLE
does this mod balance game or makes it easier?

### ISSUE THREAD

**Issue by LEGOL2** [Potobc/MHGU-Rebalanced-Mod#1]
I couldn't find a clean answer in readme. This mod basically buffs all weapons MV, but doesn't mention any monster hp buffs. For me it seems like it makes game a bit easier. Could you elaborate if those changes are net neutral or indeed boost weapon DPS without monsters rebalance.

**Comment by Potobc** [comment]
Like it says at the begining of the readme, my intention with this mod was to close the power gap between weapons to put them all on an even playing field instead of having some be objectively better than others.
So while It does make the game easier for basically all weapons as most changes are buffs and there arent any monster buffs to counteract those, it shouldnt make it any easier than it previously was if you used the best weapons in the game like valor LS/HBG. In fact it should be harder as those were nerfed and got similar times to the rest of the weapon+style combos.

**Comment by LEGOL2** [comment]
Thanks for answer! I chose sword and shield and didn't read all changes for other weapons. Could you add this clarification to the readme for future users?

**Comment by Potobc** [comment]
sure, I'll add it next time I update.
