### ISSUE TITLE
Solution to fixing missing platform icon prompts?

### ISSUE THREAD

**Issue by Scorrahz** [Potobc/MHGU-Rebalanced-Mod#2]
Okay so I'm using the HD mod compatible version but I realized that even when selecting the PlayStation icon version for this mod that several of the icons are missing. Example: Main menu "Press O to start" from the HD mod gets overwritten and reset back to "Press A to start" like in the unmodded version of the game. There are also things such as the icon for scrolling left and right to the item bar being reset back to X and Y instead of Square and O respectively or the weapon preview window showing the incorrect prompts as well. Is there a way to apply only the gameplay changes while not overwriting the HD mod button prompt changes? I know this mod has to be loaded before the HD one to take effect so that's why I'm asking. If there's no solution or if asking for a solution is too much of an ask then let me know and I'll just live with it! Would just be nice to fix the inconsistencies is all ^^ Thank you in advance for reading! (Oh and idk if it's relevant but I am on Ryujinx playing MHGU)
![Ryujinx_Ahkt395xKT](https://github.com/user-attachments/assets/d8000135-90da-4c38-98e9-56d4501fc818)
b-3945-4eb6-b6a4-4b29caf259da)
![Ryujinx_qOUlVHG2rx](https://github.com/user-attachments/assets/5c3e330f-953d-4b11-826f-d1452b886900)
![Ryujinx_fdeEYBmRtn](https://github.com/user-attachments/assets/5cff6f17-cd34-4d78-8195-0cf2a1f8f07a)
![Ryujinx_JYmaYgoYMM](https://github.com/user-attachments/assets/7d6cfce7-b63c-4887-abaa-e92e81738dbf)
![Ryujinx_EUgSK6dA87](https://github.com/user-attachments/assets/5bcf3363-91c6-4311-b30c-d65fdfac3e74)

**Comment by Potobc** [comment]
Looked into it and its not an issue with Rebalanced as the file that conflicts with the HD mod doesn't affect the buttons on quests, only on the Hub. The actual issue seems to be due to the "Weakness Icons" mod I made, where the playstation layout has the Nintendo buttons instead of the Playstation buttons (If you arent using this mod please tell me because then the issue is something else).
Once I have time I'll fix it.

**Comment by Scorrahz** [comment]
Hi! I was using the weakness icon mod and just reinstalled rebalanced and HD mod to clear it out and the issue still persists without the weakness icon mod installed. I made sure to wipe all mods I had installed and reinstalled them as per instructions and nothing has changed from my initial issue besides the fact I have no weakness icons now since I removed them.

**Comment by Potobc** [comment]
Not sure then, because my HUD looks fine with only Rebalanced and the HD mod installed 
![imagen](https://github.com/user-attachments/assets/e7cb836a-ba50-41d8-9824-0c7ef8607d22)

The logo will always show "Press A" because I added the "Rebalanced" subtitle to it, but that file only has that one button so it shouldnt affect anything else. DM me on discord if you want because I think its gonna be easier to resolve through there.

**Comment by Scorrahz** [comment]
Yeah hm, maybe I really did miss something. Where might I find your Discord?
